### ISSUE TITLE
new tools 

### ISSUE THREAD

**Issue by xxcriticxx** [notoco/univ#4]
@notoco / @kodiwpigulce

sonarr/radarr/jackett/SABnzbd nowe narzedzia do zabawy na weekend czekam na review na kwp

zycze milej zabawy

**Comment by notoco** [comment]
Daj szczegóły bo nie wiem o co chodzi.

**Comment by xxcriticxx** [comment]
sa to narzedzia ktore automatycznie sciagaja nowe odcinki z torrentow / usenetow. poczytaj troche na necie napewno was zainteresuja. wiekszasc programow posiada wersie polsko jezykowa.
